### ISSUE TITLE
Not rendering views

### ISSUE THREAD

**Issue by jonlb** [lykmapipo/sails-police#2]
Question - I just installed this module for sails and walked through the setup instructions. When I go to http://localhost:1337/signup I get an error:

{
  "message": "Could not render view \"auth/signup\".  Tried locating view file @ \"D:\repos\hsplanner\views\auth\signup\".",
  "code": "E_VIEW_FAILED",
  "status": 500,
  "view": {
    "name": "auth/signup",
    "root": "D:\repos\hsplanner\views",
    "defaultEngine": "hbs",
    "ext": ".hbs"
  }
}

Do I need to provide the views? If so, do you have default ones that I can copy as a starting point?

Thanks,
Jon Bomgardner

**Comment by lykmapipo** [comment]
@jonlb 

Yes you need to provide the view. [Default ones are located in views](https://github.com/lykmapipo/sails-police/tree/master/views/auth)

**Comment by lykmapipo** [comment]
@jonlb 

Also check [public](https://github.com/lykmapipo/sails-police/tree/master/public) for front end assets

**Comment by jonlb** [comment]
@lykmapipo 

Did this happen (those not being there by default) because I changed the view engine to handlebars? If so, would it help to have a set of handlebars files to provide in the base install?

Jon
